const cardsFeatured = [
  {
    id:21,
    imgPath: "img14.png",
    title: "Business Dress",
    isNew: true,
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 55,
    images: [
      "img14.png",
      "img2.png",
      "img3.png",
      "img.png",
    ],
  },
  {
    id:22,
    imgPath: "img2.png",
    title: "Classic Dress",
    isNew: true,
    assets: true,
    price: 120,
    rating: 4.67,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "Hugo",
    category: "women's clothing",
    stock: 2,
    images: [
      "img2.png",
      "img8.png",
      "img6.png",
      "img4.png",
    ],
  },
  {
    id:23,
    imgPath: "img3.png",
    title: "Bedroom Dress",
    isNew: true,
    assets: true,
    price: 250,
    rating: 4.55,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "Lacoste",
    category: "women's clothing",
    stock: 4,
    images: [
      "img3.png",
      "img6.png",
      "img8.png",
      "img4.png",
    ],
  },
  {
    id:24,
    imgPath: "img.png",
    title: "Dress",
    isNew: false,
    assets: true,
    price: 220,
    rating: 3.9,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "Michael Kors",
    category: "women's clothing",
    stock: 6,
    images: [
      "img.png",
      "img4.png",
      "img3.png",
      "img2.png",
    ],
  },
  {
    id:25,
    imgPath: "img4.png",
    title: "Business Dress",
    isNew: true,
    assets: true,
    price: 310,
    rating: 4.1,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "Reiss",
    category: "women's clothing",
    stock: 10,
    images: [
      "img4.png",
      "img6.png",
      "img.png",
      "img2.png",
    ],
  },
  {
    id:26,
    imgPath: "img6.png",
    title: "Dress",
    isNew: false,
    assets: true,
    price: 220,
    rating: 4.8,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "New Balance",
    category: "women's clothing",
    stock: 3,
    images: [
      "img6.png",
      "img4.png",
      "img.png",
      "img3.png",
    ],
  },
  {
    id:27,
    imgPath: "img7.png",
    title: "Creative Dress",
    isNew: true,
    assets: true,
    price: 150,
    rating: 4.6,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "Ralph Lauren",
    category: "women's clothing",
    stock: 26,
    images: [
      "img7.png",
      "img8.png",
      "img6.png",
      "img4.png",
    ],
  },
  {
    id:28,
    imgPath: "img8.png",
    title: "Party Dress",
    isNew: false,
    assets: true,
    price: 180,
    rating: 3.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 25,
    images: [
      "img8.png",
      "img.png",
      "img7.png",
      "img4.png",
    ],
  },
];

export default cardsFeatured;