const cardsFeatured = [
  {
    imgPath: "img14.png",
    title: "Dress",
    isNew: true,
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 55,
    images: [
      "img14.png",
      "img2.png",
      "img3.png",
      "img.png",
    ],
  },
  {
    imgPath: "img2.png",
    title: "Dress",
    isNew: true,
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 2,
    images: [
      "img2.png",
      "img8.png",
      "img6.png",
      "img4.png",
    ],
  },
  {
    imgPath: "img3.png",
    title: "Dress",
    isNew: true,
    assets: true,
    price: 250,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 4,
    images: [
      "img3.png",
      "img6.png",
      "img8.png",
      "img4.png",
    ],
  },
  {
    imgPath: "img.png",
    title: "Dress",
    isNew: false,
    assets: true,
    price: 220,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 6,
    images: [
      "img.png",
      "img4.png",
      "img3.png",
      "img2.png",
    ],
  },
  {
    imgPath: "img4.png",
    title: "Dress",
    isNew: true,
    assets: true,
    price: 310,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 10,
    images: [
      "img4.png",
      "img6.png",
      "img.png",
      "img2.png",
    ],
  },
  {
    imgPath: "img6.png",
    title: "Dress",
    isNew: false,
    assets: true,
    price: 220,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 3,
    images: [
      "img6.png",
      "img4.png",
      "img.png",
      "img3.png",
    ],
  },
  {
    imgPath: "img7.png",
    title: "Dress",
    isNew: true,
    assets: true,
    price: 150,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 26,
    images: [
      "img7.png",
      "img8.png",
      "img6.png",
      "img4.png",
    ],
  },
  {
    imgPath: "img8.png",
    title: "Dress",
    isNew: false,
    assets: true,
    price: 180,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    category: "women's clothing",
    stock: 25,
    images: [
      "img8.png",
      "img.png",
      "img7.png",
      "img4.png",
    ],
  },
];

export default cardsFeatured;