const cardsShop = [
  {
    imgPath: "img11.png",
    title: "Dress",
    isNew: false,
    category: "Pants",
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    stock: 55,
    images: ["img11.png", "img9.png", "img12.png", "img13.png"],
  },
  {
    imgPath: "img9.png",
    title: "Dress",
    isNew: false,
    category: "Jumpsuits",
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    stock: 55,
    images: ["img9.png","img11.png", "img12.png", "img13.png"],
  },
  {
    imgPath: "img12.png",
    title: "Dress",
    isNew: false,
    category: "Tops",
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    stock: 55,
    images: ["img12.png","img11.png", "img9.png", "img13.png"],
  },
  {
    imgPath: "img13.png",
    title: "Dress",
    isNew: false,
    category: "Accessories",
    assets: true,
    price: 120,
    rating: 4.4,
    description: "Pueraria Mirifica And Study Phyto Estrogens",
    brand: "GANNI",
    stock: 55,
    images: [ "img13.png","img11.png", "img9.png", "img12.png"],
  },
];
export default cardsShop;
